import { File, ListFilter } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

export function TickerInfoTable() {
  return (
    <TooltipProvider>
      <Tabs defaultValue="income_statement">
        <div className="flex items-center">
          <TabsList>
            <TabsTrigger value="income_statement">Income Statement</TabsTrigger>
            <TabsTrigger value="balance_sheet">Balance Sheet</TabsTrigger>
            <TabsTrigger value="cash_flow">Cash Flow</TabsTrigger>
          </TabsList>
          <div className="ml-auto flex items-center gap-2">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-7 gap-1 text-sm"
                >
                  <ListFilter className="h-3.5 w-3.5" />
                  <span className="sr-only sm:not-sr-only">Filter</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Filter by</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuCheckboxItem checked>
                  Fulfilled
                </DropdownMenuCheckboxItem>
                <DropdownMenuCheckboxItem>Declined</DropdownMenuCheckboxItem>
                <DropdownMenuCheckboxItem>Refunded</DropdownMenuCheckboxItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <Button size="sm" variant="outline" className="h-7 gap-1 text-sm">
              <File className="h-3.5 w-3.5" />
              <span className="sr-only sm:not-sr-only">Export</span>
            </Button>
          </div>
        </div>
        <Card x-chunk="dashboard-05-chunk-3">
          <CardHeader className="px-7">
            <CardTitle>Quarterly Report</CardTitle>
            <Select>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="2022" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="2020">2020</SelectItem>
                <SelectItem value="2021">2021</SelectItem>
                <SelectItem value="2022">2022</SelectItem>
                <SelectItem value="2023">2023</SelectItem>
                <SelectItem value="2024">2024</SelectItem>
              </SelectContent>
            </Select>
            <div className="flex items-center gap-1">
              <Button variant="outline">Q1</Button>
              <Button variant="outline">Q2</Button>
              <Button variant="outline">Q3</Button>
              <Button variant="outline">Q4</Button>
            </div>
          </CardHeader>
          <CardContent>
            <TabsContent value="income_statement">
              <Table>
                <TableHeader>
                  <TableRow className="bg-accent">
                    <TableHead>Metric</TableHead>
                    <TableHead className="hidden sm:table-cell">Prev</TableHead>
                    <TableHead className="hidden sm:table-cell">
                      Expected
                    </TableHead>
                    <TableHead className="hidden sm:table-cell">
                      Actuall
                    </TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger>Revenue</TooltipTrigger>
                          <TooltipContent>
                            <p>
                              Revenue refers to the total amount of money
                              <br />
                              generated by a company through its business
                              <br />
                              activities, such as sales of goods or services. It
                              <br />
                              is a key financial metric that indicates the
                              <br />
                              company &apos;s ability to generate income.
                            </p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </TableCell>
                    <TableCell className="hidden sm:table-cell">
                      26.04B
                    </TableCell>
                    <TableCell className="hidden sm:table-cell">
                      26.03B
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      26.04B
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger> Operating expense</TooltipTrigger>
                          <TooltipContent>
                            <p>
                              Operating expenses are the costs associated with
                              <br />
                              running a business&apos;s day-to-day operations. These
                              <br />
                              expenses are separate from the cost of goods sold
                              <br />
                              and include items such as rent, utilities,
                              <br />
                              salaries, and marketing expenses.
                            </p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </TableCell>
                    <TableCell className="hidden sm:table-cell">
                      3.40B
                    </TableCell>
                    <TableCell className="hidden sm:table-cell">
                      3.50B
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      3.50B
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger>Net Income</TooltipTrigger>
                          <TooltipContent>
                            <p>
                              Net income is the total amount of money a company
                              <br />
                              has left over after all expenses have been
                              deducted
                              <br />
                              from its revenue. It is a key financial metric
                              that
                              <br />
                              indicates the company&apos;s profitability.
                            </p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </TableCell>
                    <TableCell className="hidden sm:table-cell">
                      6.04B
                    </TableCell>
                    <TableCell className="hidden sm:table-cell">
                      6.03B
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      6.04B
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger>EPS</TooltipTrigger>
                          <TooltipContent>
                            <p>
                              Earnings per share (EPS) is a financial metric
                              that
                              <br />
                              indicates the company&apos;s profitability on a
                              per-share
                              <br />
                              basis. It is calculated by dividing the company&apos;s
                              net
                              <br />
                              income by the number of outstanding shares.
                            </p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </TableCell>
                    <TableCell className="hidden sm:table-cell">1.24</TableCell>
                    <TableCell className="hidden sm:table-cell">1.23</TableCell>
                    <TableCell className="hidden md:table-cell">1.24</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger>Dividend</TooltipTrigger>
                          <TooltipContent>
                            <p>
                              A dividend is a payment made by a company to its{" "}
                              <br />
                              shareholders, usually in the form of cash or
                              additional
                              <br />
                              shares. It is a way for companies to share their
                              profits <br />
                              with their investors.
                            </p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </TableCell>
                    <TableCell className="hidden sm:table-cell">0.18</TableCell>
                    <TableCell className="hidden sm:table-cell">0.18</TableCell>
                    <TableCell className="hidden md:table-cell">0.18</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </TabsContent>
          </CardContent>
        </Card>
      </Tabs>
    </TooltipProvider>
  );
}
